usb: xhci: Avoid use xhci_plat_phytium_pe220x when OF disabled
xhci_plat_phytium_pe220x is only defined when OF is enabled.
This would cause a compile error:

drivers/usb/host/xhci-plat.c:532:33: error: ‘xhci_plat_phytium_pe220x’ undeclared here (not in a function); did you mean ‘xhci_plat_runtime_resume’?
  { "PHYT0039", (kernel_ulong_t)&xhci_plat_phytium_pe220x },
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
                                 xhci_plat_runtime_resume
  CC [M]  drivers/usb/dwc3/core.o

It should be moved.

Reported-by: jianghaoa <jianghaoa@uniontech.com>
Signed-off-by: guanwentao <guanwentao@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>